config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :users
  resources :comments
  resources :categories
  resources :sessions

  root to: 'home#home'
  get '/about', to: 'home#about'
  get '/blog', to: 'home#blog'
  get '/terms', to: 'home#terms'
  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/register', to: 'users#new'
  get '/home', to: redirect('/')

  
end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :items
validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :item
belongs_to :user
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  has_many :comments
   has_many :users, through: :comments

  validates :category, presence: true
  validates :name, presence: true
  validates :identifier, presence: true

end

app/models/rental.rb
class Rental < ActiveRecord::Base
has_many :items
belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
has_secure_password

has_many :comments
has_many :rentals

validates :name, presence: true
validates :email, presence: true
validates :password, length: { minimum: 2 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

protect_from_forgery with: :exception

helper_method :current_user
before_action :require_user

def current_user
  User.find_by(id: session["user_id"])  
end

def require_user
if current_user.nil?
    redirect_to signin_path
end
end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

def index
@categories = Category.all 
@inventory = Item.all
end

def show
# do something with params
@category = Category.find_by(id: params["id"])
@items = @category.items
end

def new
  @category = Category.new
end

def create
cat_params = params.require(:category).permit!
  @category = Category.create(cat_params)
    if @category.valid?
      redirect_to categories_path, notice: "Category was successfully added"
    else
      render "new", alert: "Please recheck the errors below"
      Category.name
    end
end

def edit
@category = Category.find_by(id: params["id"])
end

def update
cat_params = params.require(:category).permit!
@category = Category.find_by(id: params["id"])
  @category.update(cat_params)
    if @category.valid?
      redirect_to categories_path, notice: "Category information was successfully updated"
    else
      render "edit", alert: "Please recheck the errors below"
      Category.name
    end
end

def destroy
    @category = Category.find_by(id: params["id"])
    @category.destroy
    redirect_to categories_path
end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
skip_before_action :require_user, only: [:show]

def index
@comments = Comment.all
end

def show
# do something with params
@tag = Comment.find_by(id: params["id"])
@comment = Comment.find_by(remark: @tag.id)
end

def new
end

def create
# do something with params
end

def edit
# do something with params
end

def update
# do something with params
end

def destroy
# do something with params
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

 skip_before_action :require_user

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

def index
@inventories = Item.all
@inventory = @inventories.sort_by {|h| h[:category_id]}
@category = Category.all
end

def show
# do something with params
@item = Item.find_by(id: params["id"])
@comments = @item.comments
end

def new
  @item = Item.new
  @select = Category.all 
end

def create
item_params = params.require(:item).permit(:category_id, :name, :description, :storage, :identifier, :owner, :purchase_date, :purchase_price,)
  @item = Item.create(item_params)
    if @item.valid?
      redirect_to items_path, notice: "Item added successfully"
    else 
      render "new", alert: "Please recheck the errors below"
      Item.name
    end
end
    

def edit
@item = Item.find_by(id: params["id"])
end


def update
item_params = params.require(:item).permit(:category_id, :name, :description, :storage, :identifier, :owner, :purchase_date, :purchase_price,)
@item = Item.find_by(id: params["id"])
    if @item.update_attributes(item_params)
      redirect_to item_path, notice: "Item updated successfully"
    else 
      render "edit", alert: "Please recheck the errors below"
      Item.name
    end
end

def destroy
    @item = Item.find_by(id: params["id"])
    @item.destroy
    redirect_to items_path
end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

skip_before_action :require_user

  def create
    # params["email"] => the email address
    # params["password"] => the password
    # Do authentication
    # Redirect to the root_path
    # Display a notice that login was either successful or unsuccessful

    user = User.find_by(email: params["email"])
    if user && user.authenticate(params["password"])
      session["user_id"] = user.id
      redirect_to items_path, notice: "Login successful"
    else
      redirect_to signin_path, alert: "Login unsuccessful"
    end

  end

  def destroy
    # Do sign-out
    session["user_id"] = nil
    redirect_to root_path, notice: "See ya later!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :require_user, only: [:new,:create,]

def index
@population = User.all
end

def show
# do something with params
@user = User.find_by(id: params["id"])
@comments = @user.comments
end

def new
  @user = User.new
 
end

def create
user_params = params.require(:user).permit(:name, :playa_name, :email, :password, :phone, :facebook, :description)
  @user = User.create(user_params)
    if @user.valid?
      redirect_to root_path, notice: "You're account was created successfully"
    else 
      render "new"
      User.name
    end
end

def edit
@user = User.find_by(id: params["id"])
end

def update
user_params = params.require(:user).permit(:name, :playa_name, :email, :password, :phone, :facebook, :description)
  @user = User.find_by(id: params["id"])
    if @user.update_attributes(user_params)
      redirect_to user_path, notice: "You're account was updated successfully"
    else 
      render "new", alert: "Please recheck the errors below"
      User.name
    end
end

def destroy
    @user = User.find_by(id: params["id"])
    @user.destroy
    redirect_to root_path
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<% provide(:title, 'Edit Category') %>
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <div class="container">
        <!-- Example row of columns -->

<% if @category.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><b><%= message %></b></li>
      <% end %>
    </ul>
  </div>
<% end %>

        <div class="row">
            
  <legend><h1> Add a category</h1></legend>

         <%= form_for @category do |form|%>

  <div class="form-group">
    <%= form.label :name, class: "col-lg-2 control-label" %>
   <%= form.text_field :name, class: "form-control" %>
  </div>

   <div class="form-group">
    <%= form.label :description, class: "col-lg-2 control-label" %>
   <%= form.text_area :description, class: "form-control" %>
  </div>

  <%= form.button 'Edit Category', class: "btn btn-primary" %>
 </div>
<% end %>
        
    </div>
</body>
</html>

app/views/categories/index.html.erb
<% provide(:title, 'Library') %>
<h1> The library currently has <b><%= @inventory.count %></b> items in <%= @categories.count %> different categories</h1>
<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <h4>You can jump to a category or add a new item</h4>
    <div class="col-md-3">
        <div class="list-group">
        <% @categories.each do |category| %> 
        <a href="" class="list-group-item"><%= category.name %></a>
        <% end %>
      </div></div>
      <div class="col-md-3">
      <%= link_to "Add an item", new_item_path, class: "btn btn-success" %>
      </div>
    
  </div>
</div>

<% @categories.each do |category| %> 
<h3> <%= link_to category.name, category %></h3>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
     <th>Available?</th>
      <th>Item Name</th>
      <th>Desc</th>
      <th>Storage spot</th>
      <th>identifier</th>
         <th></th>
          </tr>
  </thead>
<tbody>
  
  </tbody>
</table> 




<%end %>

app/views/categories/new.html.erb
<% provide(:title, 'Add Category') %>
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <div class="container">
        <!-- Example row of columns -->

        <div class="row">

<% if @category.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><b><%= message %></b></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <legend><h1> Add a category</h1></legend>

         <%= form_for @category do |form|%>

  <div class="form-group">
    <%= form.label :name, class: "col-lg-2 control-label" %>
   <%= form.text_field :name, class: "form-control", placeholder: "Please enter a simple and distinct name" %>
  </div>

   <div class="form-group">
    <%= form.label :description, class: "col-lg-2 control-label" %>
   <%= form.text_area :description, class: "form-control", placeholder: "Please enter a detailed description so people understand the items that exist in this category" %>
  </div>

  <%= form.button 'Add Category', class: "btn btn-primary" %>
 </div>
<% end %>
        
    </div>
</body>
</html>

app/views/categories/show.html.erb
<% provide(:title, @category.name) %>
  
<h1> <%= @category.name %></h1>
<p><%= @category.description %></p>
<div class="container">
  <!-- Example row of columns -->
  <div class="row">

<table class="table table-striped table-hover ">
  <thead>
    <tr>
     <th>Available?</th>
      <th>Item Name</th>
      <th>Desc</th>
      <th>Storage spot</th>
      <th>identifier</th>
         <th></th>
          </tr>
  </thead>
<tbody>
  <% @items.each do |item| %>
    <tr>
      <td></td>
      <td><%= link_to item.name, item_path(item) %>

      <td><%= item.description %></td>
      <td><%= item.storage %></td>
      <td><%= item.identifier %></td>
       <td><%= link_to "Edit", edit_item_path(item) %></td>
      
    </tr>
<% end %>
  </tbody>
</table> 
    
  </div>
</div>

app/views/comments/index.html.erb
<% provide(:title, 'Comments') %>


<h1> There are <b><%= @comments.count %></b> comments on this site </h1>
  <% @comments.each do |item| %>

    <tr>
      
      
      <%= item.user_id %></td>
      <td><%= item.item_id %></td>
      <td><%= item.remark %></td>
      
    </tr>
<% end %>

app/views/comments/show.html.erb
<% provide(:title, 'comments') %>
  

  
  <% @tag.each do |item| %>

    <tr>
      
      
      <%= item.user_id %></td>
      <td><%= item.item_id %></td>
      <td><%= item.remark %></td>
      
    </tr>
<% end %>

app/views/home/about.html.erb
<h1> About this application</h1>
<p> I started this project to connect the members of the Kellogg student body in new ways. The goal of the project is to create an application to answer a question I often find myself asking: "Which of the 1000+ students, which I may not even know, are interested in doing ____ with me soon?"</p>

<p>The project started originated in KIEI 925 - Startup Programming and Management</p>
 
<p>If you have any questions or comments, please reach out:
</br><a href="mailto:josh@joshborin.com?Subject=Hey%20there%20Josh" target="_top">Josh@joshborin.com</a>
</br><a href="https://twitter.com/joshborin">@joshborin</a> on Twitter</p>

app/views/home/blog.html.erb
<!DOCTYPE html>
<html>
<body>

<h1>Blog</h1>

<p>Blog goes here <p>


<p>Thanks for visiting!</p>

</body>
</html>

app/views/home/home.html.erb
<% provide(:jumbotron, '
      <h1>Mystopia Equipment Checkout</h1>
      <p>The place where Mystopians checkout equipment owned by the camp.</p>
       <p><a class="btn btn-primary btn-lg" role="button" href="/items">Browse library &raquo;</a></p>
  '.html_safe)%>


  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-4">
        <h2>Project Details</h2>
        <p>This project was started to manage Mystopia's assets. Learn more about the project here </p>
        <p><a class="btn btn-primary" href="/about" role="button">About &raquo;</a></p>
    
      </div>
      <div class="col-md-4">
        <h2>Placeholder</h2>
        <p>This placeholder text should help these three columns look better together.  </p>
        <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
     </div>
      <div class="col-md-4">
        <h2>Blog and News</h2>
        <p>Check out the latest news about the application. Posts published weekly</p>
        <p><a class="btn btn-primary" href="/blog" role="button" >View the blog &raquo;</a></p>
      </div>
    </div>

app/views/home/register.html.erb
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>

<body>
    <div class="container">
        <!-- Example row of columns -->

        <div class="row">
            <div class="col-md-6 col-md-offset-3">
            <h2 class="text-center">Ready to get started?</h2>
        <p class="text-info text-center">All you need is an @kellogg.northwestern.edu email</p><br>
                    
                        <div class="panel panel-primary">
                    

                    <div class="panel-body">
                        <form class="form-horizontal">
                            <fieldset>
                                <div class="form-group">
                                    <label class="col-lg-2 control-label" for=
                                    "inputFirstname">First Name</label>

                                    <div class="col-lg-10">
                                        <input class="form-control" id=
                                        "inputFirstname" placeholder=
                                        "First Name" type="text">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-lg-2 control-label" for=
                                    "inputLastname">Last Name</label>

                                    <div class="col-lg-10">
                                        <input class="form-control" id=
                                        "inputLastname" placeholder="Last Name"
                                        type="text">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-lg-2 control-label" for=
                                    "inputEmail">Email</label>

                                    <div class="col-lg-10">
                                        <input class="form-control" id=
                                        "inputEmail" placeholder="Email" type=
                                        "text">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-lg-2 control-label" for=
                                    "inputPassword">Password</label>

                                    <div class="col-lg-10">
                                        <input class="form-control" id=
                                        "inputPassword" placeholder="Password"
                                        type="password">

                                    <div class="checkbox">
                                        <label><input type="checkbox">You have read and agree to the <a href="/terms">Terms of service</a>.</label>
                                    </div>

                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-lg-10 col-lg-offset-2">
                                        <button class="btn btn-success" type=
                                        "submit">Create my account</button>
                                        
                                        
                                    </div>
                                </div>
                                	<div class="well well-sm"> Already have an account? <a href="/signin" ><u>  Sign in here &raquo;</u></a>
                                	</div>
                            </fieldset>
                        </form>
                    </div>
               
            </div>
        </div>

        
    </div>

</body>
</html>

app/views/home/terms.html.erb
<h1> Terms and Conditions</h1>
<p> Here are our terms and conditions</p>

app/views/items/edit.html.erb
<% provide(:title, 'Edit Item') %>
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <div class="container">
        <!-- Example row of columns -->

        <div class="row">
            
  <legend><h1> Edit item</h1></legend>

         
 <%= form_for @item, :html => {:class => "form-horizontal"}  do |form|%>
  <%= render 'shared/error_messages', object: @item %>
 
<div class="form-group">
    <%= form.label :category_id, class: "col-lg-2 control-label" %>
   <div class="col-lg-2">
   <%= form.select :category_id, Category.all.collect{ |c| [c.name, c.id] },{}, html_options = {class: "form-control"} %>
  </div>
</div>
  <div class="form-group">
    <%= form.label :name, class: "col-lg-2 control-label" %>
    <div class="col-lg-6">
    <%= form.text_field :name, class: "form-control", placeholder: "enter item name" %>
    </div>
  </div>
<div class="form-group">
    <%= form.label :description, class: "col-lg-2 control-label" %>
    <div class="col-lg-6">
    <%= form.text_area :description, class: "form-control", placeholder: "please enter an item description" %>
    </div>
  </div>

<div class="form-group">
    <%= form.label :storage, class: "col-lg-2 control-label" %>
    <div class="col-lg-6">
    <%= form.text_field :storage, class: "form-control", placeholder: "where is it stored?" %>
    </div>
  </div>

<div class="form-group">
    <%= form.label :identifier, class: "col-lg-2 control-label" %>
    <div class="col-lg-6">
    <%= form.text_field :identifier, class: "form-control", placeholder: "enter the identifier" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :owner, class: "col-lg-2 control-label" %>
    <div class="col-lg-6">
    <%= form.text_field :owner, class: "form-control", placeholder: "who owns it?" %>
    </div>
  </div>

<div class="form-group">
    <%= form.label :purchase_date, class: "col-lg-2 control-label" %>
    <div class="col-lg-6">
    <%= form.text_field :purchase_date, class: "form-control", placeholder: "when was it purchased?" %>
    </div>
  </div>

<div class="form-group">
    <%= form.label :purchase_price, class: "col-lg-2 control-label" %>
    <div class="col-lg-6">
    <%= form.text_field :purchase_price, class: "form-control", placeholder: "how much was it? " %>
    </div>
  </div>

<div class="form-group">
    <%= form.label " ", class: "col-lg-2 control-label" %>
    <div class="col-lg-6">
    <%= form.button 'Edit item', class: "btn btn-success" %> &nbsp; <%= link_to "Cancel", item_path, class: "btn btn-warning"  %> 
    </div>
  </div>


  
 </div>
<% end %>
        
  <br>
</div>
   
   <legend><h4>You can also delete the item from the library. This is unreversible. </h4> </legend> 
<%= link_to "Delete", item_path, method: :delete, data: {confirm:'Are you really sure? THIS BUTTON WORKS'}, class: "btn btn-danger"  %> 
  
</body>
</html>

app/views/items/index.html.erb
<% provide(:title, 'Inventory') %>
<h1> The library currently has <b><%= @inventories.count %></b> items </h1>
<div class="container">
<!-- Example row of columns -->
<div class="row">
<table class="table table-striped table-hover ">
   <thead>
      <tr>
         <th>Category</th>
         <th>Item Name</th>
         <th>Desc</th>
         <th>Storage spot</th>
         <th>identifier</th>
         <th>Available?</th>
         <th></th>
      </tr>
   </thead>
   <tbody>
      <% @inventory.each do |item| %>
      <tr>
         <td><%= link_to item.category.name, category_path( item.category_id)%></td>
         <td><a href="/items/<%= item.id %>"><%= item.name %></a></td>
         <td><%= item.description %></td>
         <td><%= item.storage %></td>
         <td><%= item.identifier %></td>
         <td></td>
         <td><%= link_to "Edit", edit_item_path(item) %></td>
      </tr>
      <% end %>
   </tbody>
</table>
<div class="container">
   <!-- Example row of columns -->
   <div class="row">
      <div class=".col-md-6 .col-md-offset-3">
         <div class="btn-toolbar">
            <div class="btn-group">
               <%= link_to "Add an item", new_item_path, class: "btn btn-lg btn-primary" %>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/items/show.html.erb
<% provide(:title, @item.name) %>

<hr class="">
<div class="container target">
    <div class="row">
        <div class="col-sm-10">
             <h1 class=""><%= @item.name %> </h1>
             <p class="lead"> <b>Description:</b> <%= @item.description %> </p>
<br>
        </div>
      <div class="col-sm-2"><a href="/users" class="pull-right"><img title="profile image" class="img-circle img-responsive" src="http://www.rlsandbox.com/img/profile.jpg"></a>

        </div>
    </div>
  <br>
    <div class="row">
        <div class="col-sm-6">
            <!--left col-->
            <ul class="list-group">
                <li class="list-group-item text-muted" contenteditable="false">Details</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Category</strong></span> <%= link_to @item.category.name, category_path( @item.category_id)%></li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Storage:</strong></span> <%= @item.storage %></li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Identifier:</strong></span> <%= @item.identifier %></li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Owner:</strong></span> <%= @item.owner %></li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Purchased on:</strong></span> <%= @item.purchase_date %></li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Original price:</strong></span> <%= @item.purchase_price %></li>
            </ul>
           
            
                <%= link_to "Edit item", edit_item_path, class: "btn  btn-primary"%>  

                
        </div>
        <!--/col-3-->
        <div class="col-sm-6" contenteditable="false" style="">
            <div class="panel panel-default">
                <div class="panel-heading">Comments about <%= @item.name %></div>
                <div class="panel-body"> 
      <% @comments.each do |comment| %>
      <blockquote>
  <p><%= comment.body %></p><small><%= link_to comment.user.name, user_path(comment.user) %> </small>
</blockquote>
 <% end %>
</div>
            </div>
           

           </div>
        </div>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>Mystopia Equipment</title>
  
<!-- Font Awesome -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

<!-- Bootswatch CDN -->
<link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.2/spacelab/bootstrap.min.css" rel="stylesheet">


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<!-- Bootstrap -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="jquery.backstretch.min.js"></script>

  <%= csrf_meta_tags %>


  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->

 

     <!-- Alerts -->
      <% if notice %>
        <div class="alert alert-success" role="alert"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>
      
  <a href="#Top"></a>
  </head>
<body>
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Mystopia Equipment Checkout" , home_path, class: "navbar-brand"  %>
      </div>
      <div class="navbar-collapse collapse navbar-inverse-collapse">
         <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Browse items" , items_path%></li> 
         <li><%= link_to "About" , about_path%></li>       
        <li>              
                <% if current_user %>
                <%= link_to "My Account" , user_path(current_user)%>
                <% else %>
                <%= link_to "Sign in" , signin_path%>
                <% end %>
            </li>
            <li>
              
                <% if current_user %>
                <%= link_to "Sign out", signout_path %>
                <% end %>
            </li>
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar -->
  <% if current_page?(root_path) %>
  <% if content_for?(:jumbotron) %>
    <div class="jumbotron">
      <div class="container">
        <%= yield :jumbotron %>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="container">
<% end %>

<%= yield %>
<footer>
    <hr>
      <p class="pull-right">
        <%= link_to '<span class="glyphicon-class glyphicon glyphicon-chevron-up"></span> Back to top'.html_safe, '#Top' %>
      </p>
      <p>
        &copy; 2015 
        &bull;
        <a href="/blog">Blog</a></li>
        &bull;
        <a href="/terms">Terms</a></li>
      </p>
    </footer>
     </div> <!-- /container -->

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<h1><a href="#">Here is a list of users</a></h1>
<% @population.each do |person|%>
<ul>
<li><%= link_to person.name, user_path(person) %></li>
</ul><% end %>

app/views/users/show.html.erb
<% provide(:title, 'Account page') %>

<hr class="">
<div class="container target">
    <div class="row">
        <div class="col-sm-10">
             <h1 class=""><%= @user.name %> </h1>
           <div class="btn-group"><%= link_to "Edit my details", edit_user_path(current_user), class: "btn  btn-default"%></div> 

    
<br>
        </div>
      <div class="col-sm-2"><a href="/users" class="pull-right"><img title="profile image" class="img-circle img-responsive" src="http://www.rlsandbox.com/img/profile.jpg"></a>

        </div>
    </div>
  <br>
    <div class="row">
        <div class="col-sm-3">
            <!--left col-->
            <ul class="list-group">
                <li class="list-group-item text-muted" contenteditable="false">Details</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Playa Name</strong></span> <%= @user.playa_name %></li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Email</strong></span> <%= @user.email %></li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Phone</strong></span> <%= @user.phone %></li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong>Items owned</strong></span> #</li>
              
            </ul>
           
            <div class="panel panel-default">
                <div class="panel-heading">Social Media</div>
                <div class="panel-body">  <i class="fa fa-facebook fa-2x"><a href="https://www.facebook.com/<%= @user.facebook %>"><%= image_tag "FB-f-Logo__blue_50.png"%></a></i>  

                </div>
            </div>
        </div>
        <!--/col-3-->
        <div class="col-sm-9" contenteditable="false" style="">
            <div class="panel panel-default">
                <div class="panel-heading"><%= @user.playa_name %>'s Bio</div>
                <div class="panel-body"> <%= @user.description %></div>
            </div>
            
            <div class="panel panel-default">
                <div class="panel-heading"><%= @user.playa_name %>'s Comments</div>
                <div class="panel-body"> 
      <% @comments.each do |comment| %>
      <blockquote>
  
</blockquote>
 <% end %>
</div>
            </div>
           

           </div>
        </div>
        